#pragma once

//Mapping texture id
#define TILE_MAP 0
#define BODY_SOPHIA 1
#define BARREL_SOPHIA 2
#define WHEEL_SOPHIA 4
#define AXEL_SOPHIA_LEFT 5

#define GET_OUT_OF_CAR_ANI 3

#define JASON_IDLE_LEFT 6
#define JASON_IDLE_RIGHT 7
#define JASON_GO_LEFT 8
#define JASON_GO_RIGHT 9
#define JASON_CRAWL_LEFT 10
#define JASON_CRAWL_RIGHT 11
#define JASON_CLIMB_UP 12
#define JASON_JUMP_LEFT 18
#define JASON_JUMP_RIGHT 19

#define JASON_O_UP 13
#define JASON_O_DOWN 14
#define JASON_O_LEFT 15
#define JASON_O_RIGHT 16
#define JASON_O_DIE 17

#define SOPHIA_BODY_SHIFT_RIGHT 20
#define SOPHIA_BODY_SHIFT_LEFT 21
#define AXEL_SOPHIA_RIGHT 22


// Scene ID
#define MAP_1_BACKGROUND 0
#define MAP_1_ACTORS 1
#define PHYSICS_SCENE 2

//Animation state ID
#define BODY_CAR_IDLE_LEFT 0
#define BODY_CAR_IDLE_RIGHT 1
#define CAR_CHANGE_DIRECTION 2

#define BARREL_IDLE_LEFT 0
#define BARREL_IDLE_RIGHT 1
#define BARREL_IDLE_TOP 2
#define BARREL_LOOK_UP_RIGHT 3
#define BARREL_LOOK_UP_LEFT 4


#define JASON_CRAWL_IDLE_LEFT 18
#define JASON_CRAWL_IDLE_RIGHT 19

#define BODY_CAR_SHIFT_RIGHT 0
#define BODY_CAR_SHIFT_LEFT 1


//
#define JASON_WALKING_SPEED 0.005
#define JASON_JUMPING_SPEED 0.2

#define GRAVITY 0.1
